README.md
Simple test with SSH key to prove connection
=> Working with a key

conf/messages
Content of opening paragraph on recipient details (transfer allowance) page has been made more generic
=> TAMC-945 altered message file to have new generic paragraph on recipient details page

public/stylesheets/tamc.css
Removed the class with font-weight: 900 to un-bold result as per Prototype.
=> TAMC-1000 Removed Class for calculator result

test/controllers/MarriageAllowanceControllerTest.scala, test/controllers/UpdateRelationshipControllerTest.scala, test/controllers/UpdateRelationshipErrorTest.scala, test/controllers/UpdateRelationshipRoutesTest.scala
Added unit tests to increase test coverage. Coverage now over 82%
=> Tamc test coverage

app/controllers/LanguageController.scala, app/utils/LanguageUtils.scala, app/views/DateOfMarriage.scala.html, app/views/multiyear/gds/eligibility_check.scala.html, app/views/multiyear/gds/lower_earner.scala.html, app/views/multiyear/gds/partners_income_question.scala.html, app/views/multiyear/pta/eligibility_check.scala.html, app/views/multiyear/pta/lower_earner.scala.html, app/views/multiyear/pta/partners_income_question.scala.html, app/views/templates/dateFields.scala.html, conf/messages, test/controllers/ContentTest.scala, test/controllers/LanguageControllerTest.scala, test/controllers/RoutesTest.scala
Content changes made on eligibility pages for GDS and PTA journey and on date of marriage page
=> TAMC-1018 content changes

app/services/EligibilityCalculatorService.scala, test/controllers/ErrorsTest.scala
replaced if-else ladder with case statement.
=> TAMC-1068 Eligibility calculator svc refactor

app/services/UpdateRelationshipService.scala, test/controllers/UpdateRelationshipControllerTest.scala, test/controllers/UpdateRelationshipErrorTest.scala, test/test_utils/TestUtility.scala
=> TAMC-1103 enhanced test coverage

public/stylesheets/tamc.css
Error flagged by @swatcats143 in CSS relating to color value updated and now passes W3
=> TAMC-1130 Fix CSS value for error

app/views/coc/divorce.scala.html
Removed previous decree absolute content
=> TAMC-1121 refactored divorce view and removed unnecessary if clause

app/config/ApplicationConfig.scala, app/views/templates/tamc_main.scala.html, conf/messages, conf/messages.cy
DDCNLS-1072: Refactored TAMC message file
=> DDCNLS-1072: Refactored TAMC message file

app/views/eligible_years.scala.html, app/views/transfer.scala.html, conf/messages, conf/messages.cy, test/controllers/ContentTest.scala, test/controllers/EligibilityCalcControllerTest.scala, test/controllers/ErrorsTest.scala, test/controllers/PtaEligibilityCalcControllerTest.scala, test/controllers/RoutesTest.scala, test/controllers/UpdateRelationshipContentTest.scala, test/controllers/UpdateRelationshipErrorTest.scala
DDCNLS-1213 : TAMC -implemented revise earnings to income.
=> DDCNLS-1213 : TAMC -implemented revise earnings to income

conf/application.conf
DDCNLS-1250 : Implemented Optimizely snippet in Marriage Allowance.
=> DDCNLS-1250 : Implemented Optimizely snippet in Marriage Allowance.

conf/application.conf
DDCNLS-1250: removed script-src
=> DDCNLS-1250: removed script-src

conf/application.conf
=> DDCNS-1250: Removed eval

conf/application.conf
DDCNLS-1250 : Testing adde online.gov.uk
=> DDCNLS-1250 : Testing adde online.gov.uk

conf/application.conf
DDCNLS-1250: Changed application config back to old
=> DDCNLS-1250: Changed application config back to old

conf/messages.cy
DDCNLS-1290 : Fixed welsh issue for variable translation.
=> DDCNLS-1290 : Fixed welsh issue for variable translation.

conf/messages.cy
DDCNLS-1213: Changed welsh text
=> DDCNLS-1213: Changed welsh text

conf/messages.cy
DDCNLS-1213- More welsh changes
=> DDCNLS-1213- More welsh changes

conf/application.conf
=> TAAS-optimizely

conf/application.conf
=> Optimizely - Added frame-src

conf/application.conf
=> removed frame-src

app/views/templates/tamc_main.scala.html
changed to optimzely parameter
=> changed to optimzely parameter

conf/application.conf
=> optimizely changes

conf/application.conf
=> Removed script src

conf/application.conf
=> Added frame-src

conf/application.conf
=> revert back the changes

conf/messages, conf/messages.cy, test/controllers/EligibilityCalcControllerTest.scala, test/controllers/PtaEligibilityCalcControllerTest.scala
@nehakannaujia - I have updated the message file and implemented the Welsh translation in the CY_message file (units tests are okay).
=> DDCNLS-1866

app/views/templates/tamc_main.scala.html
DDCNLS-2199: GDS PTA navigation bug
=> DDCNLS-2199: GDS PTA navigation bug

conf/messages, conf/messages.cy, test/controllers/EligibilityCalcControllerTest.scala, test/controllers/PtaEligibilityCalcControllerTest.scala
@nehadotkannaujia - I have removed the full stop from the error message identified by @anand462 (as well as the Welsh version). He identified it in ticket DDCNLS-2102, but I completed it in this ticket. The unit tests were updated.
=> DDCNLS-1866: Remove full stop from some error messages

public/stylesheets/tamc.css
DDCNLS-2636 : TAAS defect fix for bold text
=> DDCNLS-2636 : TAAS defect fix for bold text

conf/messages, conf/messages.cy
@pankaj2453 - please can you check my code (just updated the EN and CY message files) as they are currently hardcoded.
=> DDCNLS-3228: Add missing Scottish messaging from 'confirm earlier years'

README.md
Updated the readme file for checking the leak detection.
=> Test for leak detection

app/forms/MultiYearPartnersIncomeQuestionForm.scala, app/views/multiyear/partners_income_question.scala.html, test/controllers/EligibilityControllerTest.scala
Fixed the incorrect validation error displays in production when scottish is selected.
=> fix max limit issue if scottish or non-scottish

app/controllers/TransferController.scala, app/errors/errors.scala, app/services/TransferService.scala, test/controllers/TransferControllerTest.scala
handles dead recipient and shows relevant error page
=> DDCNLS-5953

app/views/coc/bereavement_transferor.scala.html, app/views/coc/change_in_earnings.scala.html, app/views/coc/confirm.scala.html, app/views/coc/confirm_updates.scala.html, app/views/coc/divorce.scala.html, app/views/coc/divorce_invalid_dod.scala.html, app/views/coc/divorce_select_year.scala.html, app/views/coc/email.scala.html, app/views/coc/reason_for_change.scala.html, app/views/confirm.scala.html, app/views/date_of_marriage.scala.html, app/views/errors/no_eligible_years.scala.html, app/views/errors/no_tax_year_transferor.scala.html, app/views/errors/no_year_selected.scala.html, app/views/multiyear/date_of_birth_check.scala.html, app/views/multiyear/do_you_live_in_scotland.scala.html, app/views/multiyear/do_you_want_to_apply.scala.html, app/views/multiyear/eligibility_check.scala.html, app/views/multiyear/eligibility_non_eligible_finish.scala.html, app/views/multiyear/lower_earner.scala.html, app/views/multiyear/partners_income_question.scala.html, app/views/multiyear/transfer/eligible_years.scala.html, app/views/multiyear/transfer/email.scala.html, app/views/multiyear/transfer/previous_years.scala.html, app/views/multiyear/transfer/single_year_select.scala.html, app/views/multiyear/transfer/transfer.scala.html, app/views/pta/calculator.scala.html
moves back link to top of page and adds back link to transfer-allowance page
=> DDCNLS-5938

app/config/ApplicationConfig.scala, app/controllers/LanguageController.scala, app/views/templates/tamc_main.scala.html, conf/app.routes, conf/application.conf, project/AppDependencies.scala, test/controllers/LanguageControllerTest.scala
Change to LanguageController so that it extends LanguageController in play-language and reduce the risk of malicious redirections as per DDCNOS-5463
=> Ddcnos 5463

app/views/multiyear/date_of_birth_check.scala.html, app/views/multiyear/do_you_live_in_scotland.scala.html, app/views/multiyear/do_you_want_to_apply.scala.html, app/views/multiyear/eligibility_check.scala.html, app/views/multiyear/eligibility_non_eligible_finish.scala.html, app/views/multiyear/lower_earner.scala.html, app/views/multiyear/partners_income_question.scala.html, test/controllers/ContentTest.scala
Design fix to styling on page headers and content, reducing the white space and giving consistency. For eligibility check journey initially.
=> Eligibility design fix

app/views/confirm.scala.html, app/views/date_of_marriage.scala.html, app/views/multiyear/transfer/eligible_years.scala.html, app/views/multiyear/transfer/email.scala.html, app/views/multiyear/transfer/previous_years.scala.html, app/views/multiyear/transfer/single_year_select.scala.html, app/views/multiyear/transfer/transfer.scala.html, conf/messages, conf/messages.cy
Tranfer allowance and application parts of the journey fixes styling wise. SBT tests passed cant run acceptance tests.
=> Design fix transfer allowance

app/views/coc/bereavement_recipient.scala.html, app/views/coc/bereavement_transferor.scala.html, app/views/coc/change_in_earnings.scala.html, app/views/coc/change_in_earnings_recipient.scala.html, app/views/coc/confirm.scala.html, app/views/coc/confirm_updates.scala.html, app/views/coc/divorce.scala.html, app/views/coc/divorce_invalid_dod.scala.html, app/views/coc/divorce_select_year.scala.html, app/views/coc/email.scala.html, app/views/coc/finished.scala.html, app/views/coc/reason_for_change.scala.html, app/views/coc/your_status.scala.html, app/views/templates/tamc_main.scala.html, conf/messages, conf/messages.cy
got most recent updates with master and opened PR as work has previously been done by Muhammad quite a while ago and the project owner has now confirmed the changes made are okay
=> Ddcnls 7076

build.sbt, conf/data/tax-rates.conf, project/plugins.sbt, test/controllers/EligibilityCalcControllerTest.scala, test/controllers/PtaEligibilityCalcControllerTest.scala, test/models/RelationshipRecordTest.scala, test/services/EligibilityCalculatorServiceTest.scala, test/services/TimeServiceTest.scala, test/utils/BenefitCalculatorHelperTest.scala
Reaplaced Bintray, Corrected unit tests for uprating
=> Replaced Bintray, Corrected unit tests for uprating

app/views/date_of_marriage.scala.html
- removes unnecessary markup
- adds hidden legend
Signed-off-by: Phil Sherry <philsherry@mac.com>
=> [DDCNL-3935] No legend

public/javascripts/tamc.js
- add `.attr('role', 'alert')`
Signed-off-by: Phil Sherry <philsherry@mac.com>
=> [DDCNL-3937] Audible alert for screen readers

app/views/multiyear/transfer/single_year_select.scala.html, conf/messages, conf/messages.cy
− `Do you want to apply for this extra tax year too?`
\+ `Do you want to apply for {0} too?`
Example:
> “Do you want to apply for 2019 to 2020 too?”
=> [DDCNL-3934] Content change for clarity

test/utils/BenefitCalculatorHelperTest.scala
Modified hard-coded uprating values to dynamic again in tests.
=> DDCNL-3475

app/forms/EmailForm.scala, app/uk/gov/hmrc/emailaddress/PlayFormFormatter.scala, conf/messages, project/AppDependencies.scala, test/controllers/ContentTest.scala, test/forms/EmailFormTest.scala, test/uk/gov/hmrc/emailaddress/PlayFormFormatterSpec.scala
=> Ddcnl 4521

project/AppDependencies.scala
Upgrade emailaddress library to avoid upcoming bobby rule
=> DDCNL-5132 - upgraded emailaddress

app/config/ApplicationConfig.scala, app/services/ApplicationService.scala, app/services/TimeService.scala, conf/data/tax-rates.conf, test/config/ApplicationConfigSpec.scala
=> calculate beginning year instead of using hardcoded value

app/forms/EmailForm.scala
=> Removed git from Regex

app/config/ApplicationConfig.scala, app/models/RelationshipRecord.scala, app/services/ApplicationService.scala, conf/data/tax-rates.conf, test/models/RelationshipRecordTest.scala, test/utils/BenefitCalculatorHelperTest.scala
DDCNL-5271 - Added new rates for 2022-2023 year.
=> DDCNL-5271 - Added new rates for 2022-2023 year.

app/controllers/UpdateRelationshipController.scala, app/views/coc/finished.scala.html, conf/messages, conf/messages.cy, test/controllers/UpdateRelationshipControllerTest.scala
=> Ddcnl 5505

app/views/multiyear/partners_income_question.scala.html
=> add message to hidden legend to pass the tax allowance values

app/views/multiyear/transfer/single_year_select.scala.html, conf/messages, conf/messages.cy
=> use a more descriptive legend for previous years

app/controllers/UpdateRelationshipController.scala, app/forms/coc/DivorceSelectYearForm.scala, app/services/TransferService.scala, app/viewModels/DivorceEndExplanationViewModel.scala, app/views/confirm.scala.html, app/views/multiyear/how_it_works.scala.html, conf/messages, test/controllers/UpdateRelationshipControllerTest.scala
=> Ddcnl 5412

app/models/EndRelationshipReason.scala, app/models/RecipientDetailsFormInput.scala, app/uk/gov/hmrc/emailaddress/PlayFormFormatter.scala, project/AppDependencies.scala, test/controllers/UpdateRelationshipControllerTest.scala, test/services/TransferServiceTest.scala
=> DDCNL-6052: switched references from joda time to use java time

app/views/confirm.scala.html, app/views/includes/ErrorSummary.scala.html, app/views/includes/InputDate.scala.html, app/views/includes/InputRadios.scala.html, app/views/includes/InputValue.scala.html, project/AppDependencies.scala, project/plugins.sbt
=> DDCNL-5937 Update dependencies

app/views/coc/finished.scala.html
- adds a Panel component
- removes unnecessary markup from a previous component
=> DDCNL-5508 Styling fix

build.sbt, conf/application-json-logger.xml, project/AppDependencies.scala, project/build.properties, test/controllers/ContentTest.scala, test/controllers/EligibilityCalcControllerTest.scala, test/controllers/EligibilityControllerTest.scala, test/controllers/PtaEligibilityCalcControllerTest.scala, test/controllers/TransferControllerTest.scala, test/controllers/UpdateRelationshipControllerTest.scala
=> [DDCNL-5087] Scoverage and Dependency Upgrades

app/config/ApplicationConfig.scala, app/controllers/AuthorisationController.scala, app/views/main.scala.html, conf/app.routes, conf/application.conf, project/AppDependencies.scala, project/plugins.sbt, test/controllers/AuthorisationControllerTest.scala
=> DDCNL-6450: Removed /ida/signout from logout route

app/connectors/MarriageAllowanceConnector.scala, app/errors/errors.scala, app/services/TransferService.scala, app/services/UpdateRelationshipService.scala, test/services/TransferServiceTest.scala
=> [DDCNL-4765] Adding appropriate status codes for errors

project/AppDependencies.scala
=> DDCNL-6380-prep: Updated FE assets

build.sbt
=> Fixed code coverage issue

app/views/multiyear/how_it_works.scala.html, app/views/multiyear/transfer/transfer.scala.html, conf/application.conf, project/plugins.sbt
=> DDCNL 7354

app/views/multiyear/how_it_works.scala.html, app/views/multiyear/transfer/transfer.scala.html, conf/application.conf, project/plugins.sbt
Reverts hmrc/tamc-frontend#371
=> Revert "DDCNL 7354"

conf/application.conf, project/AppDependencies.scala, project/plugins.sbt, test/controllers/AuthenticatedActionRefinerTest.scala, test/controllers/EligibilityControllerTest.scala, test/utils/BaseTest.scala, test/utils/ControllerBaseTest.scala
=> DDCNL-7610: bootstrap library upgrade

app/controllers/testonly/AcceptanceTestHelperController.scala, conf/testOnlyDoNotUseInAppConf.routes, test/controllers/testonly/AcceptanceTestHelperControllerTest.scala
=> DDCNL-7652: disabling feature flags in tests

app/config/ApplicationConfig.scala, app/controllers/EligibilityController.scala, app/views/main.scala.html, conf/application.conf, test/controllers/EligibilityControllerTest.scala
=> DDCNL-7623 changed roots for homepage

app/config/ApplicationConfig.scala, app/views/multiyear/how_it_works.scala.html, app/views/pta/calculator.scala.html, conf/application.conf, conf/messages, conf/messages.cy, test/helpers/package.scala, test/utils/ViewTestUtils.scala, test/views/multiyear/EligibilityCheckTest.scala, test/views/multiyear/HowItWorksTest.scala
=> DDCNL-7355: fix "how it works" page

app/controllers/EligibilityController.scala, app/controllers/HowItWorksController.scala, app/controllers/UpdateRelationshipController.scala, app/views/errors/session_timeout.scala.html, app/views/pta/calculator.scala.html, conf/app.routes, test/controllers/EligibilityControllerTest.scala, test/controllers/HowItWorksControllerTest.scala, test/controllers/UpdateRelationshipControllerTest.scala, test/views/multiyear/EligibilityCheckTest.scala
=> DDCNL-7626 Removed HowItWorks to its own controller

conf/application.conf
=> [DDCNL-7659] Adding accessibility frontend url to config

app/config/ApplicationConfig.scala, conf/application.conf, test/views/MainViewSpec.scala
=> Fixing the link to the report a technical problem page

app/config/ApplicationConfig.scala, conf/application.conf, test/views/MainViewSpec.scala
=> Revert changes to contact host

app/models/admin/FeatureFlag.scala
=> Implementing the SCA Wrapper Feature Flag

app/models/admin/FeatureFlag.scala, app/views/Main.scala, test/models/admin/FeatureFlagSpec.scala
=> [DDCNL-7882] Tweaks to the SCA Wrapper and feature flag reads fix

app/views/Main.scala
=> [DDCNL-7882] Fix backlink Href for Sca Wrapper

test/connectors/PertaxAuthConnectorSpec.scala, test/utils/PertaxAuthMockingHelper.scala, test/utils/WireMockHelper.scala
=> [DDCNL-8007] Making the tests not rely on pertax not running

app/config/ApplicationConfig.scala, app/views/errorTemplate.scala.html
=> DDCNL-8040: Corrected hmrcReportTechnicalIssue baseUrl in errorTemplate

project/AppDependencies.scala
=> DDCNL-8078 updated mongo feature toggle client

app/controllers/auth/PertaxAuthAction.scala
=> [DM] [PertaxAuthHeaderUpdate] Updated pertax auth header provier

app/connectors/PertaxAuthConnector.scala, app/controllers/auth/PertaxAuthAction.scala, test/connectors/PertaxAuthConnectorSpec.scala, test/controllers/auth/PertaxAuthActionSpec.scala, test/utils/PertaxAuthMockingHelper.scala, test/utils/UnitSpec.scala
=> Pertax fix

app/config/ApplicationConfig.scala, app/controllers/HowItWorksController.scala, app/controllers/UpdateRelationshipController.scala, app/views/multiyear/transfer/transfer.scala.html, conf/app.routes, conf/application.conf, test/controllers/HowItWorksControllerTest.scala, test/models/RelationshipRecordTest.scala, test/views/multiyear/transfer/TransferTest.scala
=> DDCNL-8498: Redirect Govuk entrants away from duplicated /how-it-works view

app/views/Main.scala, test/views/MainViewSpec.scala
=> DDCNL-8910: Removed UR banner and related tests

app/connectors/HttpClientResponse.scala, test/connectors/HttpClientResponseSpec.scala
=> Switching pertax unauth response to info logging

build.sbt, project/LibraryDependencies.scala, project/build.properties, project/plugins.sbt
=> DDCNL-9119 sca wrapper update

conf/messages, conf/messages.cy
=> OUTAGE_PAGE: Added outage page titles

app/views/pta/calculator.scala.html
=> Fixed error summary broken links

app/views/includes/Link.scala.html, app/views/multiyear/how_it_works.scala.html, conf/messages, conf/messages.cy, test/views/multiyear/HowItWorksTest.scala
=> Ddcnl 9505

app/views/errors/transferer_deceased.scala.html, app/views/includes/Link.scala.html, app/views/multiyear/transfer/eligible_years.scala.html, conf/messages, conf/messages.cy
=> Update pages to use new @Link include

conf/messages, conf/messages.cy
=> Ddcnl 9506: Reinstate bereavement message

app/views/multiyear/transfer/transfer.scala.html
=> DDCNL-9528 Fixed error summary broken links

app/views/Main.scala, build.sbt, project/LibraryDependencies.scala, project/plugins.sbt, test/views/MainViewSpec.scala
=> Ddcnl 9610: Only show Account menu when user is logged in

app/views/multiyear/transfer/dont_apply_current_tax_year.scala.html, test/views/multiyear/transfer/DoNotApplyTest.scala
=> DDCNL-9829 | Fix link - change the years you want to apply for

build.sbt, project/LibraryDependencies.scala
=> DDCNL-10148: remove mongo-feature-toggles-client from dependencies

app/controllers/actions/UnauthenticatedActionTransformer.scala, test/controllers/UnauthenticatedActionTransformerTest.scala
=> DDCNL-10172: Removed CL200 from unauth action and tests

app/views/includes/ErrorSummary.scala.html, conf/messages, test/views/multiyear/transfer/TransferAllowanceTest.scala
=> DDCNL 11006
